#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
COUNTER=0
while [ "$COUNTER" -lt 10 ]; do
	echo "Best School"
	if [ "$COUNTER" -eq 8 ]
	then
	    echo "Hi"
	fi
	let COUNTER=COUNTER+1
done
